name: hello_workflow
on: [push]
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: abystoma/test
          ref: main
      - name: Show me the answer
        run: cat answer.txt